### ISSUE TITLE
MCPaint 1.0 crash the finish the paint

### ISSUE THREAD

**Issue by Titoo8899** [ichttt/McPaint#1]
The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events

-----------------------------------------------------------------------------

---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  FMLPlugin (elulib-0.1.12.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CamPatchingLoader (1.12.2.minecamera-1.1.2.jar)
  offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  LoadingPlugin (Quark-r1.5-127.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  CorePlugin (SmoothFont-1.12.2-1.16-b2.jar)
  HCASM (HammerCore-1.12.2-2.0.2.2.jar)
  NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 8/28/18 7:52 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at java.util.Objects.requireNonNull(Objects.java:203)
	at ichttt.mods.mcpaint.client.gui.GuiDraw.func_146284_a(GuiDraw.java:283)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at ichttt.mods.mcpaint.client.gui.GuiDraw.func_73864_a(GuiDraw.java:246)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:203)
	at ichttt.mods.mcpaint.client.gui.GuiDraw.func_146284_a(GuiDraw.java:283)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at ichttt.mods.mcpaint.client.gui.GuiDraw.func_73864_a(GuiDraw.java:246)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: ichttt.mods.mcpaint.client.gui.GuiDraw

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Titoo8899'/46, l='MpServer', x=1095.76, y=4.00, z=-109.73]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (1097,4,-108), Chunk: (at 9,0,4 in 68,-7; contains blocks 1088,0,-112 to 1103,255,-97), Region: (2,-1; contains chunks 64,-32 to 95,-1, blocks 1024,0,-512 to 1535,255,-1)
	Level time: 93079 game time, 1000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 2 total; [EntityLumpiPlain['Lumpi'/33, l='MpServer', x=1087.76, y=4.00, z=-119.01], EntityPlayerSP['Titoo8899'/46, l='MpServer', x=1095.76, y=4.00, z=-109.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2740)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 111343872 bytes (106 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2757 67 mods loaded, 67 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                       | Version        | Source                                  | Signature                                |
	|:--------- |:------------------------ |:-------------- |:--------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                | 1.12.2         | minecraft.jar                           | None                                     |
	| UCHIJAAAA | mcp                      | 9.42           | minecraft.jar                           | None                                     |
	| UCHIJAAAA | FML                      | 8.0.99.99      | forge-1.12.2-14.23.4.2757.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                    | 14.23.4.2757   | forge-1.12.2-14.23.4.2757.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | MineCameraDummy          | 1.0.0          | minecraft.jar                           | None                                     |
	| UCHIJAAAA | smoothfontcore           | 1.12.2-1.15.1  | minecraft.jar                           | None                                     |
	| UCHIJAAAA | obfuscate                | 0.2.5          | minecraft.jar                           | None                                     |
	| UCHIJAAAA | elucore                  | 1.0            | minecraft.jar                           | None                                     |
	| UCHIJAAAA | smoothfont               | 1.12.2-1.16-b2 | SmoothFont-1.12.2-1.16-b2.jar           | None                                     |
	| UCHIJAAAA | minecamera               | 1.1.1          | 1.12.2.minecamera-1.1.2.jar             | None                                     |
	| UCHIJAAAA | securitycraft            | v1.8.7         | [1.12.x]+SecurityCraft+v1.8.7.jar       | None                                     |
	| UCHIJAAAA | fistful_of_hay           | 1.0.1          | a_fistful_of_hay-1.0.1.jar              | None                                     |
	| UCHIJAAAA | applecore                | 3.1.3          | AppleCore-mc1.12.2-3.1.3.jar            | None                                     |
	| UCHIJAAAA | arcademod                | 2.1.4          | arcademod-2.1.4-1.12.2.jar              | None                                     |
	| UCHIJAAAA | architecturecraft        | @VERSION@      | ArchitectureCraft-Mod-1.12.2.jar        | None                                     |
	| UCHIJAAAA | quark                    | r1.5-127       | Quark-r1.5-127.jar                      | None                                     |
	| UCHIJAAAA | autoreglib               | 1.3-20         | AutoRegLib-1.3-20.jar                   | None                                     |
	| UCHIJAAAA | auto_third_person        | 1.1.0          | autothirdperson-1.1.0.jar               | None                                     |
	| UCHIJAAAA | bard_mania               | 0.7.0-alpha    | bard-mania_1.12.2-0.7.0-alpha.jar       | 999640c365a8443393a1a21df2c0ede9488400e9 |
	| UCHIJAAAA | blockcraftery            | 0.1.3          | blockcraftery-0.1.3.jar                 | None                                     |
	| UCHIJAAAA | chineseworkshop          | 1.2.4          | ChineseWorkshop_1.12.2-1.2.4.jar        | None                                     |
	| UCHIJAAAA | chiselsandbits           | 14.23          | chiselsandbits-14.23.jar                | None                                     |
	| UCHIJAAAA | costumes                 | 2.0.0          | Costumes-1.12.2.jar                     | None                                     |
	| UCHIJAAAA | customnpcs               | 1.12           | CustomNPCs_1.12.2(26aug18).jar          | None                                     |
	| UCHIJAAAA | dsurround                | 3.4.9.14       | DynamicSurroundings-1.12.2-3.4.9.14.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCHIJAAAA | presets                  | 3.4.9.14       | DynamicSurroundings-1.12.2-3.4.9.14.jar | None                                     |
	| UCHIJAAAA | elevatorid               | 1.3.6          | ElevatorMod-1.12.2-1.3.6.jar            | None                                     |
	| UCHIJAAAA | fairylights              | 2.1.2          | fairylights-2.1.2-1.12.x.jar            | None                                     |
	| UCHIJAAAA | forgelin                 | 1.7.4          | Forgelin-1.7.4.jar                      | None                                     |
	| UCHIJAAAA | freelook                 | 1.2.2          | FreeLook-1.2.2.jar                      | None                                     |
	| UCHIJAAAA | cfm                      | 5.7.0          | furniture-5.7.0-1.12.2.jar              | None                                     |
	| UCHIJAAAA | gokistats                | @version@      | gokiStats-1.2.3.1.jar                   | None                                     |
	| UCHIJAAAA | grapplemod               | 1.12.2-v11.1   | grapplemod-v11.1-1.12.2.jar             | None                                     |
	| UCHIJAAAA | cgm                      | 0.6.4          | guns-0.6.4-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | hammercore               | 2.0.2.2        | HammerCore-1.12.2-2.0.2.2.jar           | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | imaginary                | 1.0.3          | imaginary-1.0.3-1.12.jar                | None                                     |
	| UCHIJAAAA | improvableskills         | 3.5.2r         | ImprovableSkills_1.12.2-3.5.2r.jar      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | lumpi                    | 0.7            | lumpi-1.12-0.7.jar                      | None                                     |
	| UCHIJAAAA | malisiscore              | 1.12.2-6.4.0   | malisiscore-1.12.2-6.4.0.jar            | None                                     |
	| UCHIJAAAA | malisisdoors             | 1.12.2-7.3.0   | malisisdoors-1.12.2-7.3.0.jar           | None                                     |
	| UCHIJAAAA | mcpaint                  | 1.0.0          | mcpaint-1.0.jar                         | None                                     |
	| UCHIJAAAA | modernlamps              | 1.0.3          | ModernLights-1.0.3_1.12.jar             | None                                     |
	| UCHIJAAAA | mrcrayfishvehiclespawner | 1.1            | Mr_Crayfish_Vehicle_Spawner_1.1.jar     | None                                     |
	| UCHIJAAAA | currency                 | 3.1.5          | NeverEnoughCurrency-4.0.1.jar           | None                                     |
	| UCHIJAAAA | notenoughroofs           | 0.8.0.0        | notenoughroofs-1.12.2-0.8.0.0.jar       | None                                     |
	| UCHIJAAAA | offlineskins             | 1.12.2-v4      | OfflineSkins-1.12.2-v4.jar              | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | randomloot               | 1.0            | Random+Loot+1.0.jar                     | None                                     |
	| UCHIJAAAA | rcroads                  | 0.2.1          | RC+Roads+0.2.1.jar                      | None                                     |
	| UCHIJAAAA | tem                      | 1.1            | Recipes+-Mod-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | redstonepaste            | 1.7.5          | redstonepaste-mc1.12-1.7.5.jar          | None                                     |
	| UCHIJAAAA | rockhounding_core        | 3.16           | rockhounding_core-1.12.2-3.16.jar       | None                                     |
	| UCHIJAAAA | gbook                    | 2.8.3          | Guidebook-1.12.2-2.8.3.jar              | None                                     |
	| UCHIJAAAA | rockhounding_rocks       | 1.12.2-3.17    | rockhounding_rocks-1.12.2-3.17.jar      | None                                     |
	| UCHIJAAAA | scarper                  | 1.0            | scarper-1.0.jar                         | None                                     |
	| UCHIJAAAA | simplifiedhorses         | 1.2            | SimplifiedHorses-v1.2-1.11-1.12.2.jar   | None                                     |
	| UCHIJAAAA | simplylight              | 0.1.0          | simplylight-0.1.0.jar                   | None                                     |
	| UCHIJAAAA | snowplusplus             | 1.1.3          | snowplusplus-1.1.3.jar                  | None                                     |
	| UCHIJAAAA | stackable                | 1.2.3          | stackable-1.12.2-1.2.3.jar              | None                                     |
	| UCHIJAAAA | vehicle                  | 0.22.0         | vehicle-mod-0.22.0-1.12.2.jar           | None                                     |
	| UCHIJAAAA | walljump                 | 1.12.2-1.1.6   | walljump-1.12.2-1.1.6.jar               | None                                     |
	| UCHIJAAAA | waystones                | 4.0.54         | Waystones_1.12.2-4.0.54.jar             | None                                     |
	| UCHIJAAAA | weaponlevels             | 2.5.0          | weaponlevels-2.5.0.jar                  | None                                     |
	| UCHIJAAAA | wearableblocks           | 1.1a           | WearableBlocks-1.12.2-1.1a.jar          | None                                     |
	| UCHIJAAAA | worldedit                | 6.1.8          | worldedit-forge-mc1.12-6.1.8-dist.jar   | None                                     |
	| UCHIJAAAA | xaerominimap             | 1.15.4         | Xaeros_Minimap_1.15.4_Forge_1.12.jar    | None                                     |
	| UCHIJAAAA | xaeroworldmap            | 1.3            | XaerosWorldMap_1.3_Forge_1.12.jar       | None                                     |
	| UCHIJAAAA | elulib                   | 0.1.12         | elulib-0.1.12.jar                       | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.3.jar)
  squeek.applecore.asm.TransformerModuleHandler
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
ForgelinPlugin (Forgelin-1.7.4.jar)
  
CamPatchingLoader (1.12.2.minecamera-1.1.2.jar)
  com.porpit.minecamera.transform.CamTransformer
offlineskins (OfflineSkins-1.12.2-v4-core.jar)
  lain.mods.skins.asm.ASMTransformer
LoadingPlugin (Quark-r1.5-127.jar)
  vazkii.quark.base.asm.ClassTransformer
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.9.14.jar)
  org.blockartistry.DynSurround.asm.Transformer
CorePlugin (SmoothFont-1.12.2-1.16-b2.jar)
  bre.smoothfont.asm.Transformer
HCASM (HammerCore-1.12.2-2.0.2.2.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
NWRTweak (redstonepaste-mc1.12-1.7.5.jar)
  net.fybertech.nwr.NWRTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.07' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 172 names; 240 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KYmxvY2tzIHsNCiAgICBCOkNodW5rTG9hZGVyPXRydWUNCiAgICBCOlRlc3NlcmFjdD10cnVlDQp9DQoNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KICAgIEI6Ik1vZCBCcm93c2VyIj10cnVlDQoNCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IlNtb290aCBWYW5pbGxhIEd1aXMiPXRydWUNCn0NCg0KDQpkZWJ1ZyB7DQogICAgQjpSYXl0cmFjZXI9ZmFsc2UNCiAgICBCOlphcHBlcj1mYWxzZQ0KfQ0KDQoNCml0ZW1zIHsNCiAgICBCOkFjY3VtdWxhdG9yPXRydWUNCn0NCg0KDQppd3JlbmNoIHsNCiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpHcmVlbj0yMkZGMjINCg0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpDQogICAgUzpSZWQ9RkYyMjIyDQp9DQoNCg0KbmV0d29ya2luZyB7DQogICAgQjoiT2xkIE5ldHdvcmsiPXRydWUNCn0NCg0KDQoidmFuaWxsYSBpbXByb3ZlbWVudHMiIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBmb3JjZS1zcGF3biBFbmRlciBEcmFnb24gRWdnIG9uIEVuZGVyIERyYWdvbiBkZWF0aD8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUNCn0NCg0KDQo=
Pastebin Connection: Okay.
Dependent Mods:
    -Improvable Skills (improvableskills) @3.5.2r

	Launched Version: 1.12.2-forge1.12.2-14.23.4.2757
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.07, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by ichttt** [comment]
Well that was fast.

**Comment by ichttt** [comment]
Should be fixed in 1.0.1
