### ISSUE TITLE
Crash when Chest/block entity is placed on paint

### ISSUE THREAD

**Issue by DraTrav** [ichttt/McPaint#22]
Crash when Chest/block entity is placed on paint. itll crash due to a render bug
[crash-2023-07-23_03.51.13-client.txt](https://github.com/ichttt/McPaint/files/12138319/crash-2023-07-23_03.51.13-client.txt)

**Comment by ichttt** [comment]
Fixed in 1.19.4-1.0. Will be live on curseforge and modrinth soon

**Comment by DraTrav** [comment]
Is there any chance you can backport it to 1.19.2?
