### ISSUE TITLE
Paint textures are flickering and disappearing

### ISSUE THREAD

**Issue by rinart73** [ichttt/McPaint#4]
Forge: 1.12.2-14.23.5.2768
Mod: 1.2.4

Painted textures are flickering and disappearing when looked at certain angles. Could it be because I have Optifine? If so, can you fix this?

**Comment by ichttt** [comment]
Are you using shaders?

**Comment by rinart73** [comment]
No. Another mod that could possibly affect rendering (I'm not sure) is foamfix (I will test without it soon). Please tell me what info I need to provide in order to solve the problem. Your mod is the only one that actually works on 1.12.2 (Good job, btw).

**Comment by ichttt** [comment]
Could you try disabling optimize pictures in the mcpaint config? You can find it by opening the mods list in the main Menu -> McPaint -> config. Might fix the issue

**Comment by rinart73** [comment]
Tried your suggestion, didn't work.
Apparently Optifine setting "Performance -> Render Regions" causes this. Sorry for bothering.
