### ISSUE TITLE
[1.14.4] v1.4.2 - Stamps break after single use.

### ISSUE THREAD

**Issue by Timestorm** [ichttt/McPaint#6]
**In Multiplayer Only**

Stamps works as intended until the second stamp when is glitches and doesn't stamp.

Attempting to recopy the stamp does not work.

May be related to this log output:
`[01:46:58.741] [Client thread/WARN] [minecraft/ClientPlayNetHandler]: Unknown custom packed identifier: mcpaint:channel`

**Comment by ichttt** [comment]
Thanks for the report, tell me if that log message shows up any longer. It is not the cause for this issue, but may cause other weird stuff to happen. Both issues should be fixed in 1.4.4 though
