### ISSUE TITLE
Crash Stamp

### ISSUE THREAD

**Issue by MineCrs1** [ichttt/McPaint#7]
If you take Stamp from Creative Mod and try to get into inventory - disconnect occurs

Minecraft 1.14.4
Forge 28.1.0-28.1.22
![11111](https://user-images.githubusercontent.com/55889482/65783136-368f9400-e160-11e9-9b25-ab78777cfb22.JPG)

**Comment by ichttt** [comment]
Fixed in 31d85858f2025061d942f3fd4e5c747403665141, update to v1.4.5
